#!/bin/bash

if [ -d /etc/larryshell ]
then
    CONFIGPATH="/etc/larryshell"
else
    CONFIGPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

VERSION="v1.3"

if [ "$1" = "--lurry" ] || [ "$1" = "-l" ]; then
	LARRY="Lurry" bash --init-file $CONFIGPATH/larryshellrc
elif [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
	echo -e "\nLarryShell ${VERSION}\n"
	echo -e "Made by the Devon Austin Wood-Thomas GitHub Organization\n"
	echo -e "\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\$\n"
	echo -e "--help, -h\n\tShow this dialog."
	echo -e "--lurry, -l\n\tEnable Lurry mode."
	echo -e ""
else
	bash --init-file $CONFIGPATH/larryshellrc
fi
