#!/bin/bash

SCRIPTPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#if [ $1 == "--lurry" ]; then
#	
#fi

if [ "$1" = "--lurry" ]; then
	LARRY="Lurry" bash --init-file $SCRIPTPATH/larryshellrc
else
	bash --init-file $SCRIPTPATH/larryshellrc
fi
